# Generated by Django 5.1.6 on 2025-04-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0006_alter_analysis_options_alter_chatmessage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='upgradedresume',
            name='ai_raw_response',
            field=models.JSONField(blank=True, help_text='Raw JSON response object received from the AI during rewrite/revision.', null=True),
        ),
    ]
